/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using NUnit.Framework;

using Salesforce.MarketingCloud.Client;
using Salesforce.MarketingCloud.Api;
using Salesforce.MarketingCloud.Model;

namespace Salesforce.MarketingCloud.Test
{
    /// <summary>
    ///  Class for testing EmailDefinitionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EmailDefinitionApiTests
    {
        private EmailDefinitionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = ApiTestSutFactory<EmailDefinitionApi>.Create();
        }

        [Test]
        public void GetEmailDefinitionTest()
        {
            var emailDefinition = CreateEmailDefinition();
            var createEmailDefinitionResult = instance.CreateEmailDefinition(emailDefinition);
            var emailDefinitionToRetrieveKey = createEmailDefinitionResult.DefinitionKey;

            var getEmailDefinitionResult = instance.GetEmailDefinitionByDefinitionKey(emailDefinitionToRetrieveKey);

            try
            {
                Assert.AreEqual(emailDefinition.DefinitionKey, getEmailDefinitionResult.DefinitionKey);
                Assert.AreEqual(emailDefinition.Name, getEmailDefinitionResult.Name);
                Assert.AreEqual(emailDefinition.Content.CustomerKey, getEmailDefinitionResult.Content.CustomerKey);
                Assert.AreEqual(emailDefinition.Subscriptions.List, getEmailDefinitionResult.Subscriptions.List);
            }
            finally
            {
                instance.DeleteEmailDefinitionByDefinitionKey(emailDefinitionToRetrieveKey);
            }
        }

        [Test]
        public void GetEmailDefinitionsTest()
        {
            var getEmailDefinitionsResponse = instance.GetEmailDefinitions();
            var deserializedEmailDefinitionResponse =
                JsonConvert.DeserializeObject<EmailDefinitionsResponse>(getEmailDefinitionsResponse.ToJson());

            Assert.IsNotNull(deserializedEmailDefinitionResponse.RequestId);
            Assert.IsNotNull(deserializedEmailDefinitionResponse.Definitions);
            Assert.IsNotNull(deserializedEmailDefinitionResponse.Count);
            Assert.IsNotNull(deserializedEmailDefinitionResponse.Page);
            Assert.IsNotNull(deserializedEmailDefinitionResponse.PageSize);
        }

        [Test]
        public void CreateEmailDefinitionTest()
        {
            var emailDefinition = CreateEmailDefinition();
            var createEmailDefinitionResult = instance.CreateEmailDefinition(emailDefinition);

            try
            {
                Assert.AreEqual(emailDefinition.DefinitionKey, createEmailDefinitionResult.DefinitionKey);
                Assert.AreEqual(emailDefinition.Name, createEmailDefinitionResult.Name);
                Assert.AreEqual(emailDefinition.Content.CustomerKey, createEmailDefinitionResult.Content.CustomerKey);
                Assert.AreEqual(emailDefinition.Subscriptions.List, createEmailDefinitionResult.Subscriptions.List);
            }
            finally
            {
                var createEmailDefinitionResultKey = createEmailDefinitionResult.DefinitionKey;
                instance.DeleteEmailDefinitionByDefinitionKey(createEmailDefinitionResultKey);
            }
        }

        [Test]
        public void DeleteEmailDefinitionTest()
        {
            var emailDefinition = CreateEmailDefinition();
            var createEmailDefinitionResult = instance.CreateEmailDefinition(emailDefinition);

            var emailDefinitionToDeleteKey = createEmailDefinitionResult.DefinitionKey;
            var deleteEmailDefinitionResult = instance.DeleteEmailDefinitionByDefinitionKey(emailDefinitionToDeleteKey);

            Assert.AreEqual("Success", deleteEmailDefinitionResult.Message);
            Assert.NotNull(deleteEmailDefinitionResult.RequestId);
        }

        [Test]
        public void PartiallyUpdateEmailDefinitionTest()
        {
            var emailDefinition = CreateEmailDefinition();
            emailDefinition.Description = "Definition description";

            var createEmailDefinitionResult = instance.CreateEmailDefinition(emailDefinition);
            var emailDefinitionToPartiallyUpdateKey = createEmailDefinitionResult.DefinitionKey;

            EmailDefinitionDescription updatedDescription = new EmailDefinitionDescription("Updated definition description");
            var partiallyUpdatedEmailDefinitionResult = instance.PartiallyUpdateEmailDefinition(emailDefinitionToPartiallyUpdateKey, updatedDescription);

            try
            {
                Assert.AreEqual(updatedDescription.Description, partiallyUpdatedEmailDefinitionResult.Description);

                Assert.AreEqual(emailDefinition.DefinitionKey, partiallyUpdatedEmailDefinitionResult.DefinitionKey);
                Assert.AreEqual(emailDefinition.Name, partiallyUpdatedEmailDefinitionResult.Name);
                Assert.AreEqual(emailDefinition.Content.CustomerKey, partiallyUpdatedEmailDefinitionResult.Content.CustomerKey);
                Assert.AreEqual(emailDefinition.Subscriptions.List, partiallyUpdatedEmailDefinitionResult.Subscriptions.List);
            }
            finally
            {
                instance.DeleteEmailDefinitionByDefinitionKey(emailDefinitionToPartiallyUpdateKey);
            }
        }

        private EmailDefinition CreateEmailDefinition()
        {
            var definitionKey = $"{Guid.NewGuid()}";
            var definitionName = $"{Guid.NewGuid()}";
            

            var customerKey = "81196847-3103-4072-9c08-965666384a78";
            var content = new Content(customerKey);

            var subscribersListKey = "e7942ec9-6585-405e-a3ef-506adfb45b42 - 2093832";
            var subscriptions = new Subscriptions(subscribersListKey);

            var emailDefinition = new EmailDefinition(definitionKey, definitionName, content, subscriptions);

            return emailDefinition;
        }

        private string CreateShortGuid()
        {
            return Convert.ToBase64String(Guid.NewGuid().ToByteArray());
        }
    }
}
