/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Salesforce.MarketingCloud.Client.SwaggerDateConverter;

namespace Salesforce.MarketingCloud.Model
{
    /// <summary>
    /// ResponseValidateEmail200
    /// </summary>
    [DataContract]
    public partial class ResponseValidateEmail200 :  IEquatable<ResponseValidateEmail200>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseValidateEmail200" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResponseValidateEmail200() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseValidateEmail200" /> class.
        /// </summary>
        /// <param name="email">Email address that was validated (required).</param>
        /// <param name="valid">Whether it was valid or not (required).</param>
        public ResponseValidateEmail200(string email = default(string), string valid = default(string))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new InvalidDataException("email is a required property for ResponseValidateEmail200 and cannot be null");
            }
            else
            {
                this.Email = email;
            }
            // to ensure "valid" is required (not null)
            if (valid == null)
            {
                throw new InvalidDataException("valid is a required property for ResponseValidateEmail200 and cannot be null");
            }
            else
            {
                this.Valid = valid;
            }
        }
        
        /// <summary>
        /// Email address that was validated
        /// </summary>
        /// <value>Email address that was validated</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Whether it was valid or not
        /// </summary>
        /// <value>Whether it was valid or not</value>
        [DataMember(Name="valid", EmitDefaultValue=false)]
        public string Valid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ResponseValidateEmail200 {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResponseValidateEmail200);
        }

        /// <summary>
        /// Returns true if ResponseValidateEmail200 instances are equal
        /// </summary>
        /// <param name="input">Instance of ResponseValidateEmail200 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResponseValidateEmail200 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Valid == input.Valid ||
                    (this.Valid != null &&
                    this.Valid.Equals(input.Valid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Valid != null)
                    hashCode = hashCode * 59 + this.Valid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
