/* 
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Salesforce.MarketingCloud.Api;
using Salesforce.MarketingCloud.Model;
using Salesforce.MarketingCloud.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Salesforce.MarketingCloud.Test
{
    /// <summary>
    ///  Class for testing ResponseValidateEmailDefault
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseValidateEmailDefaultTests
    {
        // TODO uncomment below to declare an instance variable for ResponseValidateEmailDefault
        //private ResponseValidateEmailDefault instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseValidateEmailDefault
            //instance = new ResponseValidateEmailDefault();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseValidateEmailDefault
        /// </summary>
        [Test]
        public void ResponseValidateEmailDefaultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseValidateEmailDefault
            //Assert.IsInstanceOfType<ResponseValidateEmailDefault> (instance, "variable 'instance' is a ResponseValidateEmailDefault");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'FailedValidation'
        /// </summary>
        [Test]
        public void FailedValidationTest()
        {
            // TODO unit test for the property 'FailedValidation'
        }
        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Test]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

    }

}
